id: P001753
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21494
  title: རང་བློ་གསལ་བའི་མེ་ལོང་ལས་མངོན་བརྗོད་ཀྱི་བསྟན་བཅོས་བསམ་འཕེལ་ནོར་བུ
  author: ''
  volumes:
    9e2ea68235a3460d855208c0529a9495:
      image_group_id: I6043
      title: ''
      volume_number: 1
      total_pages: 762
      base_file: v001.txt
