id: IDA5DDB1D
legacy_id: P001753
ocr_import_info:
  bdrc_scan_id: W21494
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T08:59:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T14:10:43.168545+00:00'
last_modified: 2022-09-01 22:11:05.603390
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21494
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW21494
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རང་བློ་གསལ་བའི་མེ་ལོང་ལས་མངོན་བརྗོད་ཀྱི་བསྟན་བཅོས་བསམ་འཕེལ་ནོར་བུ།
  author: འབྲུག་རྗེ་མཁན་པོ ༡༤་བསྟན་འཛིན་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.6174988935475851
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I6043:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6043
      total_pages: 762
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6043.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6174988935475851
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
